apiVersion: apps/v1
kind: Deployment
metadata:
  name: wine-quality-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wine-quality
  template:
    metadata:
      labels:
        app: wine-quality
    spec:
      containers:
      - name: wine-quality
        image: 056614919553.dkr.ecr.us-east-2.amazonaws.com/wine-quality-api:latest
        ports:
        - containerPort: 5001
